### ISSUE TITLE
Set up project's base configuration

### ISSUE THREAD

**Issue by narr** [narr/narr-material-ui#1]
# TODO

- [x] Initial configs like .gitignore, .gitattributes
- [x] Set up Typescript, React, Storybook, ESLint, TSLint, Prettier
- [x] Try Storybook add-ons
- [x] Add Jest
- [x] Add Material-UI
- [x] Add Styled-components
- [x] Deploy Storybook to gh-pages
- [x] Deploy Test Results to gh-pages
- [x] Test [react-live](https://github.com/FormidableLabs/react-live) with Storybook
- [x] Make a deployment version of material-ui-core
- [x] Try lerna publish to simplify the process with [commitizen-cli](https://github.com/commitizen/cz-cli)

**Comment by narr** [comment]
Done base configuration
