### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by narr** [narr/narr-material-ui#41]
- [x] fix the test report path
- [x] fix Prop Types in Storybook by adding react-docgen-typescript-loader again
- [x] don't ignore definitions.js
- [x] make a compiled commonjs module available from Typescript 
- [x] remove react-docgen-typescript-loader again because it makes 3s slower to compile in Storybook
- [x] add .npmignore
